version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: transcendence_backend
    restart: always
    working_dir: /app
    volumes:
      - /app/node_modules
      - ./backend:/app
      - db-data:/db
    ports:
      - "5555:5000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_PATH=${DATABASE_PATH}
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: transcendence_frontend
  #   restart: always
  #   working_dir: /app
  #   volumes:
  #     - ./frontend:/app  # Подключаем код фронтенда
  #     - /app/node_modules  # Исключаем node_modules
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend

volumes:
  db-data:
    driver: local
