version: "3.8"

services:
  backend:
    build: ./backend
    container_name: transcendence_backend
    restart: always
    volumes:
      - db-data:/db
    ports:
      - "3000:3000"
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    container_name: transcendence_frontend
    restart: always
    ports:
      - "8080:80"

volumes:
  db-data:
    driver: local
